#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTW.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DoAnWeb")]
	public partial class CSDLDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCHITIETDATHANG(CHITIETDATHANG instance);
    partial void UpdateCHITIETDATHANG(CHITIETDATHANG instance);
    partial void DeleteCHITIETDATHANG(CHITIETDATHANG instance);
    partial void InsertDATHANG(DATHANG instance);
    partial void UpdateDATHANG(DATHANG instance);
    partial void DeleteDATHANG(DATHANG instance);
    partial void InsertHANGSX(HANGSX instance);
    partial void UpdateHANGSX(HANGSX instance);
    partial void DeleteHANGSX(HANGSX instance);
    partial void InsertKHACHHANG(KHACHHANG instance);
    partial void UpdateKHACHHANG(KHACHHANG instance);
    partial void DeleteKHACHHANG(KHACHHANG instance);
    partial void InsertLienhe(Lienhe instance);
    partial void UpdateLienhe(Lienhe instance);
    partial void DeleteLienhe(Lienhe instance);
    partial void InsertSANPHAM(SANPHAM instance);
    partial void UpdateSANPHAM(SANPHAM instance);
    partial void DeleteSANPHAM(SANPHAM instance);
    partial void InsertTkadmin(Tkadmin instance);
    partial void UpdateTkadmin(Tkadmin instance);
    partial void DeleteTkadmin(Tkadmin instance);
    #endregion
		
		public CSDLDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DoAnWebConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public CSDLDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CSDLDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CSDLDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CSDLDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CHITIETDATHANG> CHITIETDATHANGs
		{
			get
			{
				return this.GetTable<CHITIETDATHANG>();
			}
		}
		
		public System.Data.Linq.Table<Trangbia> Trangbias
		{
			get
			{
				return this.GetTable<Trangbia>();
			}
		}
		
		public System.Data.Linq.Table<DATHANG> DATHANGs
		{
			get
			{
				return this.GetTable<DATHANG>();
			}
		}
		
		public System.Data.Linq.Table<HANGSX> HANGSXes
		{
			get
			{
				return this.GetTable<HANGSX>();
			}
		}
		
		public System.Data.Linq.Table<KHACHHANG> KHACHHANGs
		{
			get
			{
				return this.GetTable<KHACHHANG>();
			}
		}
		
		public System.Data.Linq.Table<Lienhe> Lienhes
		{
			get
			{
				return this.GetTable<Lienhe>();
			}
		}
		
		public System.Data.Linq.Table<SANPHAM> SANPHAMs
		{
			get
			{
				return this.GetTable<SANPHAM>();
			}
		}
		
		public System.Data.Linq.Table<Tkadmin> Tkadmins
		{
			get
			{
				return this.GetTable<Tkadmin>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CHITIETDATHANG")]
	public partial class CHITIETDATHANG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Madh;
		
		private int _Masp;
		
		private System.Nullable<int> _Soluong;
		
		private System.Nullable<decimal> _Gia;
		
		private EntityRef<DATHANG> _DATHANG;
		
		private EntityRef<SANPHAM> _SANPHAM;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMadhChanging(int value);
    partial void OnMadhChanged();
    partial void OnMaspChanging(int value);
    partial void OnMaspChanged();
    partial void OnSoluongChanging(System.Nullable<int> value);
    partial void OnSoluongChanged();
    partial void OnGiaChanging(System.Nullable<decimal> value);
    partial void OnGiaChanged();
    #endregion
		
		public CHITIETDATHANG()
		{
			this._DATHANG = default(EntityRef<DATHANG>);
			this._SANPHAM = default(EntityRef<SANPHAM>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Madh", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Madh
		{
			get
			{
				return this._Madh;
			}
			set
			{
				if ((this._Madh != value))
				{
					if (this._DATHANG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMadhChanging(value);
					this.SendPropertyChanging();
					this._Madh = value;
					this.SendPropertyChanged("Madh");
					this.OnMadhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Masp", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Masp
		{
			get
			{
				return this._Masp;
			}
			set
			{
				if ((this._Masp != value))
				{
					if (this._SANPHAM.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaspChanging(value);
					this.SendPropertyChanging();
					this._Masp = value;
					this.SendPropertyChanged("Masp");
					this.OnMaspChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Soluong", DbType="Int")]
		public System.Nullable<int> Soluong
		{
			get
			{
				return this._Soluong;
			}
			set
			{
				if ((this._Soluong != value))
				{
					this.OnSoluongChanging(value);
					this.SendPropertyChanging();
					this._Soluong = value;
					this.SendPropertyChanged("Soluong");
					this.OnSoluongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gia", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Gia
		{
			get
			{
				return this._Gia;
			}
			set
			{
				if ((this._Gia != value))
				{
					this.OnGiaChanging(value);
					this.SendPropertyChanging();
					this._Gia = value;
					this.SendPropertyChanged("Gia");
					this.OnGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DATHANG_CHITIETDATHANG", Storage="_DATHANG", ThisKey="Madh", OtherKey="Madh", IsForeignKey=true)]
		public DATHANG DATHANG
		{
			get
			{
				return this._DATHANG.Entity;
			}
			set
			{
				DATHANG previousValue = this._DATHANG.Entity;
				if (((previousValue != value) 
							|| (this._DATHANG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DATHANG.Entity = null;
						previousValue.CHITIETDATHANGs.Remove(this);
					}
					this._DATHANG.Entity = value;
					if ((value != null))
					{
						value.CHITIETDATHANGs.Add(this);
						this._Madh = value.Madh;
					}
					else
					{
						this._Madh = default(int);
					}
					this.SendPropertyChanged("DATHANG");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SANPHAM_CHITIETDATHANG", Storage="_SANPHAM", ThisKey="Masp", OtherKey="Masp", IsForeignKey=true)]
		public SANPHAM SANPHAM
		{
			get
			{
				return this._SANPHAM.Entity;
			}
			set
			{
				SANPHAM previousValue = this._SANPHAM.Entity;
				if (((previousValue != value) 
							|| (this._SANPHAM.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SANPHAM.Entity = null;
						previousValue.CHITIETDATHANGs.Remove(this);
					}
					this._SANPHAM.Entity = value;
					if ((value != null))
					{
						value.CHITIETDATHANGs.Add(this);
						this._Masp = value.Masp;
					}
					else
					{
						this._Masp = default(int);
					}
					this.SendPropertyChanged("SANPHAM");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Trangbia")]
	public partial class Trangbia
	{
		
		private string _hinhanhbia;
		
		public Trangbia()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hinhanhbia", DbType="VarChar(10)")]
		public string hinhanhbia
		{
			get
			{
				return this._hinhanhbia;
			}
			set
			{
				if ((this._hinhanhbia != value))
				{
					this._hinhanhbia = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DATHANG")]
	public partial class DATHANG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Madh;
		
		private int _Makh;
		
		private System.Nullable<bool> _Dathanhtoan;
		
		private System.Nullable<System.DateTime> _Ngaydathang;
		
		private string _Ngaygiahang;
		
		private System.Nullable<bool> _Dagiaohang;
		
		private EntitySet<CHITIETDATHANG> _CHITIETDATHANGs;
		
		private EntityRef<KHACHHANG> _KHACHHANG;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMadhChanging(int value);
    partial void OnMadhChanged();
    partial void OnMakhChanging(int value);
    partial void OnMakhChanged();
    partial void OnDathanhtoanChanging(System.Nullable<bool> value);
    partial void OnDathanhtoanChanged();
    partial void OnNgaydathangChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaydathangChanged();
    partial void OnNgaygiahangChanging(string value);
    partial void OnNgaygiahangChanged();
    partial void OnDagiaohangChanging(System.Nullable<bool> value);
    partial void OnDagiaohangChanged();
    #endregion
		
		public DATHANG()
		{
			this._CHITIETDATHANGs = new EntitySet<CHITIETDATHANG>(new Action<CHITIETDATHANG>(this.attach_CHITIETDATHANGs), new Action<CHITIETDATHANG>(this.detach_CHITIETDATHANGs));
			this._KHACHHANG = default(EntityRef<KHACHHANG>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Madh", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Madh
		{
			get
			{
				return this._Madh;
			}
			set
			{
				if ((this._Madh != value))
				{
					this.OnMadhChanging(value);
					this.SendPropertyChanging();
					this._Madh = value;
					this.SendPropertyChanged("Madh");
					this.OnMadhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Makh", DbType="Int NOT NULL")]
		public int Makh
		{
			get
			{
				return this._Makh;
			}
			set
			{
				if ((this._Makh != value))
				{
					if (this._KHACHHANG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMakhChanging(value);
					this.SendPropertyChanging();
					this._Makh = value;
					this.SendPropertyChanged("Makh");
					this.OnMakhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dathanhtoan", DbType="Bit")]
		public System.Nullable<bool> Dathanhtoan
		{
			get
			{
				return this._Dathanhtoan;
			}
			set
			{
				if ((this._Dathanhtoan != value))
				{
					this.OnDathanhtoanChanging(value);
					this.SendPropertyChanging();
					this._Dathanhtoan = value;
					this.SendPropertyChanged("Dathanhtoan");
					this.OnDathanhtoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngaydathang", DbType="DateTime")]
		public System.Nullable<System.DateTime> Ngaydathang
		{
			get
			{
				return this._Ngaydathang;
			}
			set
			{
				if ((this._Ngaydathang != value))
				{
					this.OnNgaydathangChanging(value);
					this.SendPropertyChanging();
					this._Ngaydathang = value;
					this.SendPropertyChanged("Ngaydathang");
					this.OnNgaydathangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngaygiahang", DbType="NChar(10)")]
		public string Ngaygiahang
		{
			get
			{
				return this._Ngaygiahang;
			}
			set
			{
				if ((this._Ngaygiahang != value))
				{
					this.OnNgaygiahangChanging(value);
					this.SendPropertyChanging();
					this._Ngaygiahang = value;
					this.SendPropertyChanged("Ngaygiahang");
					this.OnNgaygiahangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dagiaohang", DbType="Bit")]
		public System.Nullable<bool> Dagiaohang
		{
			get
			{
				return this._Dagiaohang;
			}
			set
			{
				if ((this._Dagiaohang != value))
				{
					this.OnDagiaohangChanging(value);
					this.SendPropertyChanging();
					this._Dagiaohang = value;
					this.SendPropertyChanged("Dagiaohang");
					this.OnDagiaohangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DATHANG_CHITIETDATHANG", Storage="_CHITIETDATHANGs", ThisKey="Madh", OtherKey="Madh")]
		public EntitySet<CHITIETDATHANG> CHITIETDATHANGs
		{
			get
			{
				return this._CHITIETDATHANGs;
			}
			set
			{
				this._CHITIETDATHANGs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACHHANG_DATHANG", Storage="_KHACHHANG", ThisKey="Makh", OtherKey="Makh", IsForeignKey=true)]
		public KHACHHANG KHACHHANG
		{
			get
			{
				return this._KHACHHANG.Entity;
			}
			set
			{
				KHACHHANG previousValue = this._KHACHHANG.Entity;
				if (((previousValue != value) 
							|| (this._KHACHHANG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KHACHHANG.Entity = null;
						previousValue.DATHANGs.Remove(this);
					}
					this._KHACHHANG.Entity = value;
					if ((value != null))
					{
						value.DATHANGs.Add(this);
						this._Makh = value.Makh;
					}
					else
					{
						this._Makh = default(int);
					}
					this.SendPropertyChanged("KHACHHANG");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CHITIETDATHANGs(CHITIETDATHANG entity)
		{
			this.SendPropertyChanging();
			entity.DATHANG = this;
		}
		
		private void detach_CHITIETDATHANGs(CHITIETDATHANG entity)
		{
			this.SendPropertyChanging();
			entity.DATHANG = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HANGSX")]
	public partial class HANGSX : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Mahangsx;
		
		private string _Tenhangsx;
		
		private string _Logo;
		
		private EntitySet<SANPHAM> _SANPHAMs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMahangsxChanging(string value);
    partial void OnMahangsxChanged();
    partial void OnTenhangsxChanging(string value);
    partial void OnTenhangsxChanged();
    partial void OnLogoChanging(string value);
    partial void OnLogoChanged();
    #endregion
		
		public HANGSX()
		{
			this._SANPHAMs = new EntitySet<SANPHAM>(new Action<SANPHAM>(this.attach_SANPHAMs), new Action<SANPHAM>(this.detach_SANPHAMs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mahangsx", DbType="VarChar(30) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Mahangsx
		{
			get
			{
				return this._Mahangsx;
			}
			set
			{
				if ((this._Mahangsx != value))
				{
					this.OnMahangsxChanging(value);
					this.SendPropertyChanging();
					this._Mahangsx = value;
					this.SendPropertyChanged("Mahangsx");
					this.OnMahangsxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tenhangsx", DbType="NVarChar(20)")]
		public string Tenhangsx
		{
			get
			{
				return this._Tenhangsx;
			}
			set
			{
				if ((this._Tenhangsx != value))
				{
					this.OnTenhangsxChanging(value);
					this.SendPropertyChanging();
					this._Tenhangsx = value;
					this.SendPropertyChanged("Tenhangsx");
					this.OnTenhangsxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Logo", DbType="NVarChar(50)")]
		public string Logo
		{
			get
			{
				return this._Logo;
			}
			set
			{
				if ((this._Logo != value))
				{
					this.OnLogoChanging(value);
					this.SendPropertyChanging();
					this._Logo = value;
					this.SendPropertyChanged("Logo");
					this.OnLogoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HANGSX_SANPHAM", Storage="_SANPHAMs", ThisKey="Mahangsx", OtherKey="Mahangsx")]
		public EntitySet<SANPHAM> SANPHAMs
		{
			get
			{
				return this._SANPHAMs;
			}
			set
			{
				this._SANPHAMs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_SANPHAMs(SANPHAM entity)
		{
			this.SendPropertyChanging();
			entity.HANGSX = this;
		}
		
		private void detach_SANPHAMs(SANPHAM entity)
		{
			this.SendPropertyChanging();
			entity.HANGSX = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KHACHHANG")]
	public partial class KHACHHANG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Makh;
		
		private string _Tenkh;
		
		private string _Diachikh;
		
		private string _Sdtkh;
		
		private string _Taikhoan;
		
		private string _Matkhau;
		
		private string _Email;
		
		private System.Nullable<System.DateTime> _Ngaysinh;
		
		private EntitySet<DATHANG> _DATHANGs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMakhChanging(int value);
    partial void OnMakhChanged();
    partial void OnTenkhChanging(string value);
    partial void OnTenkhChanged();
    partial void OnDiachikhChanging(string value);
    partial void OnDiachikhChanged();
    partial void OnSdtkhChanging(string value);
    partial void OnSdtkhChanged();
    partial void OnTaikhoanChanging(string value);
    partial void OnTaikhoanChanged();
    partial void OnMatkhauChanging(string value);
    partial void OnMatkhauChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnNgaysinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaysinhChanged();
    #endregion
		
		public KHACHHANG()
		{
			this._DATHANGs = new EntitySet<DATHANG>(new Action<DATHANG>(this.attach_DATHANGs), new Action<DATHANG>(this.detach_DATHANGs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Makh", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Makh
		{
			get
			{
				return this._Makh;
			}
			set
			{
				if ((this._Makh != value))
				{
					this.OnMakhChanging(value);
					this.SendPropertyChanging();
					this._Makh = value;
					this.SendPropertyChanged("Makh");
					this.OnMakhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tenkh", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string Tenkh
		{
			get
			{
				return this._Tenkh;
			}
			set
			{
				if ((this._Tenkh != value))
				{
					this.OnTenkhChanging(value);
					this.SendPropertyChanging();
					this._Tenkh = value;
					this.SendPropertyChanged("Tenkh");
					this.OnTenkhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Diachikh", DbType="NVarChar(50)")]
		public string Diachikh
		{
			get
			{
				return this._Diachikh;
			}
			set
			{
				if ((this._Diachikh != value))
				{
					this.OnDiachikhChanging(value);
					this.SendPropertyChanging();
					this._Diachikh = value;
					this.SendPropertyChanged("Diachikh");
					this.OnDiachikhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sdtkh", DbType="VarChar(11) NOT NULL", CanBeNull=false)]
		public string Sdtkh
		{
			get
			{
				return this._Sdtkh;
			}
			set
			{
				if ((this._Sdtkh != value))
				{
					this.OnSdtkhChanging(value);
					this.SendPropertyChanging();
					this._Sdtkh = value;
					this.SendPropertyChanged("Sdtkh");
					this.OnSdtkhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Taikhoan", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Taikhoan
		{
			get
			{
				return this._Taikhoan;
			}
			set
			{
				if ((this._Taikhoan != value))
				{
					this.OnTaikhoanChanging(value);
					this.SendPropertyChanging();
					this._Taikhoan = value;
					this.SendPropertyChanged("Taikhoan");
					this.OnTaikhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Matkhau", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Matkhau
		{
			get
			{
				return this._Matkhau;
			}
			set
			{
				if ((this._Matkhau != value))
				{
					this.OnMatkhauChanging(value);
					this.SendPropertyChanging();
					this._Matkhau = value;
					this.SendPropertyChanged("Matkhau");
					this.OnMatkhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngaysinh", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> Ngaysinh
		{
			get
			{
				return this._Ngaysinh;
			}
			set
			{
				if ((this._Ngaysinh != value))
				{
					this.OnNgaysinhChanging(value);
					this.SendPropertyChanging();
					this._Ngaysinh = value;
					this.SendPropertyChanged("Ngaysinh");
					this.OnNgaysinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACHHANG_DATHANG", Storage="_DATHANGs", ThisKey="Makh", OtherKey="Makh")]
		public EntitySet<DATHANG> DATHANGs
		{
			get
			{
				return this._DATHANGs;
			}
			set
			{
				this._DATHANGs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DATHANGs(DATHANG entity)
		{
			this.SendPropertyChanging();
			entity.KHACHHANG = this;
		}
		
		private void detach_DATHANGs(DATHANG entity)
		{
			this.SendPropertyChanging();
			entity.KHACHHANG = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Lienhe")]
	public partial class Lienhe : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _manoidung;
		
		private string _chitietnoidung;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmanoidungChanging(string value);
    partial void OnmanoidungChanged();
    partial void OnchitietnoidungChanging(string value);
    partial void OnchitietnoidungChanged();
    #endregion
		
		public Lienhe()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_manoidung", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string manoidung
		{
			get
			{
				return this._manoidung;
			}
			set
			{
				if ((this._manoidung != value))
				{
					this.OnmanoidungChanging(value);
					this.SendPropertyChanging();
					this._manoidung = value;
					this.SendPropertyChanged("manoidung");
					this.OnmanoidungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_chitietnoidung", DbType="NVarChar(200)")]
		public string chitietnoidung
		{
			get
			{
				return this._chitietnoidung;
			}
			set
			{
				if ((this._chitietnoidung != value))
				{
					this.OnchitietnoidungChanging(value);
					this.SendPropertyChanging();
					this._chitietnoidung = value;
					this.SendPropertyChanged("chitietnoidung");
					this.OnchitietnoidungChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SANPHAM")]
	public partial class SANPHAM : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Masp;
		
		private string _Tensp;
		
		private string _Mahangsx;
		
		private System.Nullable<bool> _Tinhtrang;
		
		private string _Manhinh;
		
		private string _Hedieuhanh;
		
		private string _CPU;
		
		private string _Ram;
		
		private string _Pin;
		
		private System.Nullable<bool> _Khuyenmai;
		
		private System.Nullable<decimal> _Gia;
		
		private string _Hinhanh;
		
		private string _Bonhotrong;
		
		private System.Nullable<System.DateTime> _Ngaycapnhat;
		
		private string _Camera;
		
		private EntitySet<CHITIETDATHANG> _CHITIETDATHANGs;
		
		private EntityRef<HANGSX> _HANGSX;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaspChanging(int value);
    partial void OnMaspChanged();
    partial void OnTenspChanging(string value);
    partial void OnTenspChanged();
    partial void OnMahangsxChanging(string value);
    partial void OnMahangsxChanged();
    partial void OnTinhtrangChanging(System.Nullable<bool> value);
    partial void OnTinhtrangChanged();
    partial void OnManhinhChanging(string value);
    partial void OnManhinhChanged();
    partial void OnHedieuhanhChanging(string value);
    partial void OnHedieuhanhChanged();
    partial void OnCPUChanging(string value);
    partial void OnCPUChanged();
    partial void OnRamChanging(string value);
    partial void OnRamChanged();
    partial void OnPinChanging(string value);
    partial void OnPinChanged();
    partial void OnKhuyenmaiChanging(System.Nullable<bool> value);
    partial void OnKhuyenmaiChanged();
    partial void OnGiaChanging(System.Nullable<decimal> value);
    partial void OnGiaChanged();
    partial void OnHinhanhChanging(string value);
    partial void OnHinhanhChanged();
    partial void OnBonhotrongChanging(string value);
    partial void OnBonhotrongChanged();
    partial void OnNgaycapnhatChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaycapnhatChanged();
    partial void OnCameraChanging(string value);
    partial void OnCameraChanged();
    #endregion
		
		public SANPHAM()
		{
			this._CHITIETDATHANGs = new EntitySet<CHITIETDATHANG>(new Action<CHITIETDATHANG>(this.attach_CHITIETDATHANGs), new Action<CHITIETDATHANG>(this.detach_CHITIETDATHANGs));
			this._HANGSX = default(EntityRef<HANGSX>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Masp", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Masp
		{
			get
			{
				return this._Masp;
			}
			set
			{
				if ((this._Masp != value))
				{
					this.OnMaspChanging(value);
					this.SendPropertyChanging();
					this._Masp = value;
					this.SendPropertyChanged("Masp");
					this.OnMaspChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tensp", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string Tensp
		{
			get
			{
				return this._Tensp;
			}
			set
			{
				if ((this._Tensp != value))
				{
					this.OnTenspChanging(value);
					this.SendPropertyChanging();
					this._Tensp = value;
					this.SendPropertyChanged("Tensp");
					this.OnTenspChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mahangsx", DbType="VarChar(30)")]
		public string Mahangsx
		{
			get
			{
				return this._Mahangsx;
			}
			set
			{
				if ((this._Mahangsx != value))
				{
					if (this._HANGSX.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMahangsxChanging(value);
					this.SendPropertyChanging();
					this._Mahangsx = value;
					this.SendPropertyChanged("Mahangsx");
					this.OnMahangsxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tinhtrang", DbType="Bit")]
		public System.Nullable<bool> Tinhtrang
		{
			get
			{
				return this._Tinhtrang;
			}
			set
			{
				if ((this._Tinhtrang != value))
				{
					this.OnTinhtrangChanging(value);
					this.SendPropertyChanging();
					this._Tinhtrang = value;
					this.SendPropertyChanged("Tinhtrang");
					this.OnTinhtrangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Manhinh", DbType="VarChar(20)")]
		public string Manhinh
		{
			get
			{
				return this._Manhinh;
			}
			set
			{
				if ((this._Manhinh != value))
				{
					this.OnManhinhChanging(value);
					this.SendPropertyChanging();
					this._Manhinh = value;
					this.SendPropertyChanged("Manhinh");
					this.OnManhinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hedieuhanh", DbType="VarChar(30)")]
		public string Hedieuhanh
		{
			get
			{
				return this._Hedieuhanh;
			}
			set
			{
				if ((this._Hedieuhanh != value))
				{
					this.OnHedieuhanhChanging(value);
					this.SendPropertyChanging();
					this._Hedieuhanh = value;
					this.SendPropertyChanged("Hedieuhanh");
					this.OnHedieuhanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CPU", DbType="VarChar(50)")]
		public string CPU
		{
			get
			{
				return this._CPU;
			}
			set
			{
				if ((this._CPU != value))
				{
					this.OnCPUChanging(value);
					this.SendPropertyChanging();
					this._CPU = value;
					this.SendPropertyChanged("CPU");
					this.OnCPUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ram", DbType="VarChar(30)")]
		public string Ram
		{
			get
			{
				return this._Ram;
			}
			set
			{
				if ((this._Ram != value))
				{
					this.OnRamChanging(value);
					this.SendPropertyChanging();
					this._Ram = value;
					this.SendPropertyChanged("Ram");
					this.OnRamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pin", DbType="VarChar(30)")]
		public string Pin
		{
			get
			{
				return this._Pin;
			}
			set
			{
				if ((this._Pin != value))
				{
					this.OnPinChanging(value);
					this.SendPropertyChanging();
					this._Pin = value;
					this.SendPropertyChanged("Pin");
					this.OnPinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Khuyenmai", DbType="Bit")]
		public System.Nullable<bool> Khuyenmai
		{
			get
			{
				return this._Khuyenmai;
			}
			set
			{
				if ((this._Khuyenmai != value))
				{
					this.OnKhuyenmaiChanging(value);
					this.SendPropertyChanging();
					this._Khuyenmai = value;
					this.SendPropertyChanged("Khuyenmai");
					this.OnKhuyenmaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gia", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Gia
		{
			get
			{
				return this._Gia;
			}
			set
			{
				if ((this._Gia != value))
				{
					this.OnGiaChanging(value);
					this.SendPropertyChanging();
					this._Gia = value;
					this.SendPropertyChanged("Gia");
					this.OnGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hinhanh", DbType="VarChar(50)")]
		public string Hinhanh
		{
			get
			{
				return this._Hinhanh;
			}
			set
			{
				if ((this._Hinhanh != value))
				{
					this.OnHinhanhChanging(value);
					this.SendPropertyChanging();
					this._Hinhanh = value;
					this.SendPropertyChanged("Hinhanh");
					this.OnHinhanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bonhotrong", DbType="VarChar(20)")]
		public string Bonhotrong
		{
			get
			{
				return this._Bonhotrong;
			}
			set
			{
				if ((this._Bonhotrong != value))
				{
					this.OnBonhotrongChanging(value);
					this.SendPropertyChanging();
					this._Bonhotrong = value;
					this.SendPropertyChanged("Bonhotrong");
					this.OnBonhotrongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngaycapnhat", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> Ngaycapnhat
		{
			get
			{
				return this._Ngaycapnhat;
			}
			set
			{
				if ((this._Ngaycapnhat != value))
				{
					this.OnNgaycapnhatChanging(value);
					this.SendPropertyChanging();
					this._Ngaycapnhat = value;
					this.SendPropertyChanged("Ngaycapnhat");
					this.OnNgaycapnhatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Camera", DbType="VarChar(50)")]
		public string Camera
		{
			get
			{
				return this._Camera;
			}
			set
			{
				if ((this._Camera != value))
				{
					this.OnCameraChanging(value);
					this.SendPropertyChanging();
					this._Camera = value;
					this.SendPropertyChanged("Camera");
					this.OnCameraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SANPHAM_CHITIETDATHANG", Storage="_CHITIETDATHANGs", ThisKey="Masp", OtherKey="Masp")]
		public EntitySet<CHITIETDATHANG> CHITIETDATHANGs
		{
			get
			{
				return this._CHITIETDATHANGs;
			}
			set
			{
				this._CHITIETDATHANGs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HANGSX_SANPHAM", Storage="_HANGSX", ThisKey="Mahangsx", OtherKey="Mahangsx", IsForeignKey=true)]
		public HANGSX HANGSX
		{
			get
			{
				return this._HANGSX.Entity;
			}
			set
			{
				HANGSX previousValue = this._HANGSX.Entity;
				if (((previousValue != value) 
							|| (this._HANGSX.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HANGSX.Entity = null;
						previousValue.SANPHAMs.Remove(this);
					}
					this._HANGSX.Entity = value;
					if ((value != null))
					{
						value.SANPHAMs.Add(this);
						this._Mahangsx = value.Mahangsx;
					}
					else
					{
						this._Mahangsx = default(string);
					}
					this.SendPropertyChanged("HANGSX");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CHITIETDATHANGs(CHITIETDATHANG entity)
		{
			this.SendPropertyChanging();
			entity.SANPHAM = this;
		}
		
		private void detach_CHITIETDATHANGs(CHITIETDATHANG entity)
		{
			this.SendPropertyChanging();
			entity.SANPHAM = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tkadmin")]
	public partial class Tkadmin : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maadmin;
		
		private string _pass;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaadminChanging(string value);
    partial void OnmaadminChanged();
    partial void OnpassChanging(string value);
    partial void OnpassChanged();
    #endregion
		
		public Tkadmin()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maadmin", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maadmin
		{
			get
			{
				return this._maadmin;
			}
			set
			{
				if ((this._maadmin != value))
				{
					this.OnmaadminChanging(value);
					this.SendPropertyChanging();
					this._maadmin = value;
					this.SendPropertyChanged("maadmin");
					this.OnmaadminChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pass", DbType="VarChar(20)")]
		public string pass
		{
			get
			{
				return this._pass;
			}
			set
			{
				if ((this._pass != value))
				{
					this.OnpassChanging(value);
					this.SendPropertyChanging();
					this._pass = value;
					this.SendPropertyChanged("pass");
					this.OnpassChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
